##
# Pterodactyl Panel Docker Setup by ccarney
##
version: '2'
services:

##
# Panel Cache
##
  cache:
    image: memcached:1.4-alpine
    restart: always

##
# The main service.
# Ensure that all variables/data is correct.
##
  panel:
    container_name: pterodactyl-panel
    depends_on:
    - cache
    env_file: .env
    image: quay.io/ccarney/pterodactyl-panel:v0.6.4
    restart: always
    volumes:
    - ./data:/data
