##
# Optional Services, Recommended to rename to docker-compose.override.yml
##
version: '2'
services:

##
# On initial setup, run "docker-compose run --rm certbot certonly --webroot -w /ssl/.webroot
# -d <domain>" to recieve a certificate
##
  # certbot:
  #   command: renew
  #   image: certbot/certbot:v1.13.0
  #   volumes:
  #   - ./ssl:/etc/letsencrypt

##
# If you rely on another MySQL/MariaDB instance, this can be safely removed.
# Make sure to remove the dependency from the panel
##
  mysql:
    env_file: .env
    volumes:
    - ./db:/var/lib/mysql
    image: mariadb:10.1
  panel:
    depends_on:
    - mysql
    volumes:
    - ./ssl:/ssl
    - ./ssl/.webroot/.well-known:/var/www/html/public/.well-known

##
# If you don't plan on running the daemon on the same machine, 
# you may comment the section below.
##
  daemon:
    image: quay.io/ccarney/pterodactyl-daemon:v0.4.2
    depends_on:
    - panel
    ports:
    -  8080:8080
    restart: always
    volumes:
    - /srv/daemon/config:/srv/daemon/config
    - /srv/daemon/packs:/srv/daemon/packs
    - /srv/daemon/scripts:/srv/daemon/scripts
    - /srv/daemon-data:/srv/daemon-data

    - /tmp/pterodactyl:/tmp/pterodactyl

    - /var/run/docker.sock:/var/run/docker.sock
