##
# Pterodactyl Panel Docker Setup by ccarney
##
version: '2'
services:

##
# Certbot (Let's Encrypt)
# This service provides automatic SSL for the panel.
# when in doubt, use it. Please check certbot's documentation
# for use in a container.
##
  certbot:
    command: renew
    image: certbot/certbot
    volumes:
    - ./letsencrypt:/etc/letsencrypt

##
# MariaDB (MySQL) Server
# If you rely on another MySQL/MariaDB instance, 
# this can be safely removed. If you want to have 
# your game servers be able to access this, be sure 
# to declare your ports.
##
  mysql:
    env_file: .env
    image: mariadb:10.1
    restart: always
    volumes:
    - ./mysql_db:/var/lib/mysql

##
# Panel Cache
# This service is required for the panel to function.
# You can use either redis or memcached, but redis
# is provided by default here.
##
  cache:
    container_name: pterodactyl-cache
    image: redis:alpine
    restart: always

##
# Pterodactyl Panel
# This is the main service that will be seen publically.
##
  panel:
    container_name: pterodactyl-panel
    depends_on:
    - cache
    - mysql
    env_file: .env
    image: quay.io/ccarney/pterodactyl-panel:v0.7.0-beta
    restart: always
    volumes:
    - ./data:/data

    # Let's Encrypt webroot functionality
    # - ./letsencrypt:/etc/letsencrypt
    # - ./letsencrypt/.webroot/.well-known:/var/www/html/public
    ports:
    - 80:80
    - 443:443

##
# Pterodactyl Daemon
# If you don't plan on running the daemon on the same machine, 
# you may comment the section below.
##
  daemon:
    container_name: pterodactyl-daemon
    depends_on:
    - panel
    image: quay.io/ccarney/pterodactyl-daemon:v0.5.0-beta
    ports:
    -  8080:8080
    privileged: true
    restart: always
    volumes:
    - /srv/daemon/config:/srv/daemon/config
    - /srv/daemon/packs:/srv/daemon/packs
    - /srv/daemon-data:/srv/daemon-data

    - /tmp/pterodactyl:/tmp/pterodactyl

    # Docker socket, this is required to function properly.
    - /var/run/docker.sock:/var/run/docker.sock
