##
# Pterodactyl Panel Docker Setup by ccarney
##
version: '2'
services:

##
# Panel Cache
##
  cache:
    image: memcached:1.4-alpine

##
# The main service.
# Ensure that all variables/data is correct.
##
  panel:
    container_name: pterodactyl-panel
    depends_on:
    - cache
    env_file: .env
    image: quay.io/ccarney/pterodactyl-panel:testing
    ports:
    - 80:80
    - 443:443
    restart: always
    volumes:
    - ./data:/data

##
# If you don't plan on running the daemon on the same machine, comment the section below.
##
  daemon:
    image: quay.io/ccarney/pterodactyl-daemon:v0.4.2
    depends_on:
    - panel
    ports:
    -  8080:8080
    restart: always
    volumes:
    - /srv/daemon/config:/srv/daemon/config
    - /srv/daemon/packs:/srv/daemon/packs
    - /srv/daemon/scripts:/srv/daemon/scripts
    - /srv/daemon-data:/srv/daemon-data

    - /tmp/pterodactyl:/tmp/pterodactyl

    - /var/run/docker.sock:/var/run/docker.sock
